#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import glob
import fire
import shlex # Handle `'` and `"` in filenames.

MUSIC_DIR = os.path.expanduser('~/Music/wav')

"""
Slows down .wav audio for the A E S T H E T I C
"""

def slow(file, *speeds):
    """
    Extract dfu binaries into /tmp/ and run dfu-util to install new bindings.
    """
    name, ext = os.path.splitext(file)

    if not speeds:
        speeds = [56, 64, 72, 81, 90]

    for s in speeds:
        path = shlex.quote(os.path.join(MUSIC_DIR, f"{name}_{s}{ext}"))
        os.system(f"sox {shlex.quote(file)} {path} speed {s/100}")

if __name__ == "__main__":
    fire.Fire(slow)

